server:
  port: 8888

eureka:
  client:
     serviceUrl:
      defaultZone: http://localhost:1025/eureka/

spring:
  cloud:
    gateway:
      routes:
      - id: bulletscreen
        uri: lb://bullet
        predicates:
        - Path=/bullet/info/**
      - id: bulletscreen
        uri: lb:ws://bullet
        predicates:
        - Path=/bullet/**

management:
  endpoints:
    web:
      exposure:
        include: refresh
